version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: acp4pogynvaeidfj
      MYSQL_PASSWORD: jc31d2qyy7h9jv5jn1u9uosjksxzaizw
      MYSQL_DATABASE: dd

  web:
    build: .
    # volumes:
    #   - .:/code
    ports:
      - "8080:8080"
    environment:
      - MYSQL_NAME=dd
      - MYSQL_USER=acp4pogynvaeidfj
      - MYSQL_PASSWORD=jc31d2qyy7h9jv5jn1u9uosjksxzaizw
    depends_on:
      - db

volumes:
  db_data: {}
  # wordpress_data: {}